# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Bot Whatsapp

on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # CLAVE DETENERLO PARA QUE NO ME SIGA GENERANDO ARCHIVOS
      # - run: pm2 stop checkConsulado
      # - run: pm2 stop 0
      # - run: pm2 delete bot-whatsapp > /dev/null
      - run: pm2 delete bot-whatsapp || true
      

      - uses: actions/checkout@v4
        with:
          clean: false

      #- uses: actions/checkout@v3
      #  with:
      #    clean: false

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'
      #     # GITHUB_WORKSPACE: /home/chanfi/Apps/git

      # - run: npm install pm2@latest -g #install pm2 global
      - run: pm2 -V #check pm2 version
      - run: pm2 list #check pm2 list

      - run: npm i 

      - run: npm run build

      # - run: npm run start
      #running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
      - run: pm2 start dist/main.js --name bot-whatsapp

      - run: echo "Todo Okas!!"

#       - run: ln -s /home/chanfi/Runners/checkConsulado/_work/checkConsulado/sesionWSP /home/chanfi/Runners/checkConsulado/_work/checkConsulado/checkConsulado/.wwebjs_auth
# /home/opc/runners/_work/bot2/bot2

#       - run: ln -s /home/chanfi/Runners/checkConsulado/_work/checkConsulado/cacheWSP /home/chanfi/Runners/checkConsulado/_work/checkConsulado/checkConsulado/.wwebjs_cache

#       - run: npm i

#       - run: pm2 reload checkConsulado
#         # working-directory: ${{env.working-directory}}
# #run: npm run build --if-present
# #    - run: echo "pruebita andando ok"

# # FUENTE: https://stackoverflow.com/questions/72360263/how-to-checkout-a-repository-outside-of-the-workspace-in-github-actions
# # steps:
# #   - uses: actions/checkout@v3
# #   - run: mv /path/to/my/folder /path/to/my/target

#running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
# - run: pm2 start index.js --watch -i max
#- run: pm2 start npm run start
